language: java

jdk:
  - oraclejdk7
  - oraclejdk8

script:
  - echo ============ Build and test =====================
  - mvn -DskipTests=true -Dmaven.javadoc.skip=true -B -V  clean test

notifications:
  email:
    recipients:
      - christiangda@gmail.com
    on_success: change
    on_failure: always